modLoader="javafml"
loaderVersion="[35,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/runelic/issues"
license="ARR"

[[mods]]
modId="runelic"
updateJSONURL="https://updates.blamejared.com/get?n=runelic&gv=1.16.4"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''