modLoader = "javafml"
license = "ARR"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/runelic/issues"

[[mods]]
modId = "runelic"
version = "26.1.2.0"
displayName = "Runelic"
updateJSONURL = "https://updates.blamejared.com/get?n=runelic&gv=26.1.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/runelic"
logoFile = "logo_runelic.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Adds the Runelic font system to the game."

[[mixins]]
config = "runelic.common.mixins.json"

[[mixins]]
config = "runelic.neoforge.mixins.json"

[[dependencies.runelic]]
modId = "minecraft"
type = "required"
versionRange = "26.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.runelic]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.runelic]]
modId = "bookshelf"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

